name: Release

on:
  release:
    types: [created]

jobs:
  call-workflow:
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v2
    with:
      josm-revision: "r18173"
    secrets: inherit
    permissions:
      contents: write

