name: Release

on:
  release:
    types: [created]

permissions:
  id-token: write
  attestations: write
  contents: write
  packages: write
  checks: write

jobs:
  call-workflow:
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v3
    with:
      josm-revision: "r19044"
    secrets: inherit
